services:

   mysql:
        image: mysql:8.0
        container_name: 'gridcp-mysql'
        cap_add:
                - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=gridcp
            - MYSQL_ROOT_PASSWORD=mysqlPass!123
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
            - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - gridcp-api_default

   api:
        image: 'ghcr.io/gridcp/docker-php-8.5.2:main'
        container_name: 'gridcp-api'
        restart: always
        command:
          - sh -c "mkdir -p var"
          - sh -c "chmod g+s /var/www/var"
          - sh -c "chown -R www-data /var/www/var"
          - sh -c "mkdir -p vendor"
          - sh -c "chmod g+s /var/www/vendor"
          - sh -c "chown -R www-data /var/www/vendor"
        depends_on:
            - mysql
        ports:
             - "80:80"
        volumes:
            - ./app:/var/www
            - symfony_app_var:/var/www/var
        networks:
          - gridcp-api_default


   rabbitmq:
      image: rabbitmq:3.12.9-management-alpine
      container_name: 'rabbitmq'
      restart: always
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
      networks:
        - gridcp-api_default

   maildev:
    image:  maildev/maildev
    container_name: 'maildev'
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8090:80"
      - "25:25"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - gridcp-api_default


volumes:
    symfony_app_var:
    db:
        driver: local
    rabbitmq-data:
        driver: local
    rabbitmq-log:
        driver: local

networks:
  gridcp-api_default:
    external: true