api_node_create:
  resource:
    path: ../src/Node/Presentation/Rest/
    namespace: GridCP\Node\Presentation\Rest
  type: attribute

api_get_node:
  resource:
    path: ../src/Node/Presentation/Rest/
    namespace: GridCP\Node\Presentation\Rest
  type: attribute

api_get_node_by_uuid:
    resource:
        path: ../src/Node/Presentation/Rest/
        namespace: GridCP\Node\Presentation\Rest
    type: attribute

api_delete_node:
    resource:
        path: ../src/Node/Presentation/Rest/
        namespace: GridCP\Node\Presentation\Rest
    type: attribute

api_get_free_ips_node_by_uuid:
    resource:
        path: ../src/Node/Presentation/Rest/
        namespace: GridCP\Node\Presentation\Rest
    type: attribute

api_get_pve_nodes:
  resource:
    path: ../src/Proxmox/Node/Presentation/Rest/
    namespace: GridCP\Proxmox\Node\Presentation\Rest
  type: attribute

get_all_os:
  resource:
    path: ../src/Proxmox/Os/Presentation/Rest/
    namespace: GridCP\Proxmox\Os\Presentation\Rest
  type: attribute