fos_rest:
  versioning:
    enabled: true
    default_version: 'V1'

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: ^/api/V2, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  routing_loader: false
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
