security:
  enable_authenticator_manager: true
  password_hashers:
    GridCP\Entity\User: 'auto'
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost: 15
  providers:
    app_user_provider:
      entity:
        class: GridCP\Security\Common\Infrastructure\DB\MySQL\Entity\AuthEntity
        property: uuid
  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/login_check
        provider: app_user_provider
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt:

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider

  access_control:
      - { path: ^/api/v1/node, roles: PUBLIC_ACCESS }
      - { path: ^/api/v1/proxmox, roles: PUBLIC_ACCESS }